package com.umterrick.weatherbot.enums;

public enum BotState {
    START,
    HELP,
    ASK_MAIN_CITY,
    ASK_ADDITIONAL_CITY,
    SHOW_MAIN_MENU,
    TAKE_WEATHER,
    TAKE_FORECAST,
    CHANGE_CITY,
    CHANGE_MAIN_CITY,
    SAVE_MAIN_CITY,
    CHANGE_ADDITIONAL_CITY,
    HANDLE_COMMAND,
    SHOW_HELP_MENU,
    SCHEDULE_MESSAGE,
}
